"""ErrorReport model: one problem the extension ran into, with its evidence.

Sent by the extension (POST /api/error-reports) only while the user is signed
in to this cloud. Unlike a telemetry event it carries what a diagnosis needs:
the model and provider, the context size, the tail of the request and the
response. The columns below are what the problem report page lists and groups
by; everything else stays in ``payload``, which is read only for the drill-down
and for one sample per group (services/diagnostics_service).
"""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, Index, String, Text

from src.models.base import Base


class ErrorReport(Base):
    """One reported problem."""

    __tablename__ = "error_reports"
    __table_args__ = (
        # The report page reads one user's reports over a created_at range;
        # the single-column index on user_id cannot serve the range too.
        Index("ix_error_reports_user_created", "user_id", "created_at"),
    )

    # Generated by the extension (a uuid), so a retried upload names the same
    # row and the insert can ignore it (ON CONFLICT DO NOTHING).
    id = Column(String, primary_key=True)
    # CASCADE, unlike telemetry_events: a report carries the tail of a
    # conversation, which must not outlive the account it belongs to.
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    organization_id = Column(String, ForeignKey("organizations.id", ondelete="SET NULL"), nullable=True, index=True)
    # Not a FK, as on telemetry_events: a report can name a task that is never
    # stored as a row. Deleting a stored task deletes its reports explicitly
    # (services/share_service.delete_tasks).
    task_id = Column(String, nullable=True, index=True)
    category = Column(String, nullable=False, index=True)
    provider = Column(String, nullable=True)
    model_id = Column(String, nullable=True, index=True)
    mode = Column(String, nullable=True)
    app_version = Column(String, nullable=True)
    # "vscode" or "cli" (services/client_kind): which client sent the report.
    client_kind = Column(String, nullable=False, default="vscode", server_default="vscode")
    tool_name = Column(String, nullable=True)
    summary = Column(Text, nullable=False)
    # The grouping key: category, tool and the first line of the message with
    # the parts that vary between occurrences blanked (services/problem_catalogue).
    signature = Column(String, nullable=False, index=True)
    # When it happened, by the extension's clock; created_at is when it arrived.
    occurred_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(
        DateTime(timezone=True), nullable=False, index=True, default=lambda: datetime.now(timezone.utc)
    )
    # The whole report as received (JSON text), for the drill-down.
    payload = Column(Text, nullable=False)
