"""LLM exchanges: every request the agent sent to the model and its answer.

Recorded by the extension (POST /api/llm-exchanges) only while the user is
signed in AND has switched recording on (``DatasetSettings``). An exchange is
stored incrementally: ``payload`` keeps the record as received, whose
conversation is a delta against ``base_id`` (another exchange of the same task),
and whose large texts (system prompt, tool definitions, large wire fields) are
references into ``llm_blobs``. services/exchange_reconstruction rebuilds every
request in full; services/dataset_export turns them into a training dataset.
See ai_plans/2026-10-02_llm-exchange-dataset.md.
"""

from datetime import datetime, timezone

from sqlalchemy import BigInteger, Boolean, Column, DateTime, ForeignKey, Index, Integer, String, Text

from src.models.base import Base, TimestampMixin


def _now():
    return datetime.now(timezone.utc)


class LlmExchange(Base):
    """One request to the model and its answer."""

    __tablename__ = "llm_exchanges"
    __table_args__ = (
        # The dataset page and the export read one user's exchanges over a range.
        Index("ix_llm_exchanges_user_created", "user_id", "created_at"),
        # The reconstruction reads one task's exchanges.
        Index("ix_llm_exchanges_user_task", "user_id", "task_id"),
    )

    # Generated by the extension (a uuid): a retried upload names the same row.
    id = Column(String, primary_key=True)
    # CASCADE: an exchange carries a whole conversation, which must not outlive
    # the account it belongs to.
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    organization_id = Column(String, ForeignKey("organizations.id", ondelete="SET NULL"), nullable=True)
    # Not a FK: exchanges are recorded whether or not the task is synced as a
    # row. Deleting a stored task deletes its exchanges explicitly
    # (services/share_service.delete_tasks).
    task_id = Column(String, nullable=False)
    # The exchange this one is a delta of; NULL for a full snapshot.
    base_id = Column(String, nullable=True)
    sequence = Column(Integer, nullable=False, default=0)
    occurred_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, index=True, default=_now)
    provider = Column(String, nullable=True)
    model_id = Column(String, nullable=True, index=True)
    mode = Column(String, nullable=True)
    workspace_path = Column(String, nullable=True)
    # "vscode" or "cli" (services/client_kind): which client recorded it.
    client_kind = Column(String, nullable=False, default="vscode", server_default="vscode")
    # completed, error or aborted (an unknown value from a newer client is kept).
    status = Column(String, nullable=False)
    finish_reason = Column(String, nullable=True)
    input_tokens = Column(BigInteger, nullable=False, default=0, server_default="0")
    output_tokens = Column(BigInteger, nullable=False, default=0, server_default="0")
    tool_call_count = Column(Integer, nullable=False, default=0, server_default="0")
    has_wire = Column(Boolean, nullable=False, default=False, server_default="0")
    # Comma-separated quality issues (services/exchange_quality): from the
    # static check at ingest, refreshed when the outcome arrives. Empty = clean
    # as far as the exchange alone can tell; the export re-checks with the
    # whole task in view.
    issues = Column(String, nullable=False, default="")
    # The record as received, blob texts moved to llm_blobs (JSON text).
    payload = Column(Text, nullable=False)
    # The tool call outcomes the extension sent after the tools ran (JSON text).
    outcome = Column(Text, nullable=True)


class LlmBlob(Base):
    """A large text an exchange refers to by its SHA-256 (system prompt, tools).

    Per task, not per user: deleting a task deletes its blobs without counting
    references. The extension sends a text once per chain, so the duplication
    is one system prompt per task.
    """

    __tablename__ = "llm_blobs"

    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    task_id = Column(String, primary_key=True)
    sha256 = Column(String, primary_key=True)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=_now)


class DatasetSettings(Base, TimestampMixin):
    """The user's dataset switch and export preferences."""

    __tablename__ = "dataset_settings"

    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    # Off until the user switches it on: a recording carries every prompt and
    # every file the model read.
    recording_enabled = Column(Boolean, nullable=False, default=False, server_default="0")
    # The user's own terms the anonymizer replaces (company, client, product
    # names), one per line.
    anonymize_terms = Column(Text, nullable=True)
