"""LLM exchange recording: the endpoints, the contract with the extension, storage and deletion.

The contract fixture (tests/fixtures/llm_exchanges_recorder.json) is what the
extension's real recorder uploads for a scripted task; it is regenerated by
src/core/dataset/__tests__/ExchangeRecorder.fixture.spec.ts. Here the same
records are posted and the reconstruction must give back every request exactly.
"""

import copy
import gzip
import hashlib
import json
from pathlib import Path

import pytest
from sqlalchemy import func, select

from src.dependencies import get_current_user
from src.models.llm_exchange import DatasetSettings, LlmBlob, LlmExchange
from src.models.task import Task
from src.models.user import User
from src.services.exchange_reconstruction import load_task
from src.services.share_service import delete_tasks

from tests.web_helpers import _override_current_user, _seed_user

FIXTURE = json.loads((Path(__file__).parent / "fixtures" / "llm_exchanges_recorder.json").read_text())


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _exchange(**overrides):
    """A small full snapshot shaped like the recorder's."""
    body = {
        "id": "ex-1",
        "taskId": "task-1",
        "sequence": 0,
        "occurredAt": 1790000000000,
        "retryAttempt": 0,
        "modelId": "glm-5.3",
        "provider": "openai",
        "mode": "code",
        "workspacePath": "/home/alice/work/acme-portal",
        "request": {
            "system": {"sha256": _sha("sys"), "text": "sys"},
            "tools": {"sha256": _sha("[]"), "text": "[]"},
            "messages": {"keep": 0, "append": [{"role": "user", "content": "hi"}]},
            "messageCount": 1,
            "params": {"temperature": 0},
        },
        "response": {"text": "hello", "usage": {"inputTokens": 10, "outputTokens": 2}},
        "status": "completed",
    }
    body.update(overrides)
    return body


def _post(client, path, body, *, compress=True):
    data = json.dumps(body).encode()
    headers = {"Content-Type": "application/json"}
    if compress:
        data = gzip.compress(data)
        headers["Content-Encoding"] = "gzip"
    return client.post(path, content=data, headers=headers)


@pytest.fixture
def authed(client):
    _override_current_user(client.app)
    yield client
    client.app.dependency_overrides.pop(get_current_user, None)


async def _record_on(db_session, user_id="user_test"):
    await _seed_user(db_session, user_id=user_id, email=f"{user_id}@example.org")
    db_session.add(DatasetSettings(user_id=user_id, recording_enabled=True))
    await db_session.commit()


async def _count(session_factory, model):
    async with session_factory() as s:
        return await s.scalar(select(func.count()).select_from(model))


# --- the switch ------------------------------------------------------------------


def test_every_endpoint_needs_the_bearer_token(client):
    assert client.get("/api/llm-exchanges/config").status_code == 401
    assert _post(client, "/api/llm-exchanges", _exchange()).status_code == 401
    assert _post(client, "/api/llm-exchanges/outcome", {}).status_code == 401


async def test_recording_is_off_until_the_user_switches_it_on(authed, db_session, session_factory):
    await _seed_user(db_session)

    assert authed.get("/api/llm-exchanges/config").json() == {"enabled": False}
    resp = _post(authed, "/api/llm-exchanges", _exchange())
    assert resp.json() == {"success": True, "stored": False, "recording": False}
    assert await _count(session_factory, LlmExchange) == 0

    db_session.add(DatasetSettings(user_id="user_test", recording_enabled=True))
    await db_session.commit()
    assert authed.get("/api/llm-exchanges/config").json() == {"enabled": True}


async def test_a_deployment_without_telemetry_records_nothing(authed, db_session, session_factory, monkeypatch):
    from config.settings import settings as app_settings

    await _record_on(db_session)
    monkeypatch.setattr(app_settings, "telemetry_enabled", False)

    assert authed.get("/api/llm-exchanges/config").json() == {"enabled": False}
    assert _post(authed, "/api/llm-exchanges", _exchange()).json()["recording"] is False
    assert await _count(session_factory, LlmExchange) == 0


# --- ingestion ---------------------------------------------------------------------


async def test_an_exchange_is_stored_with_its_columns_and_its_blobs_apart(authed, db_session, session_factory):
    await _record_on(db_session)

    resp = _post(authed, "/api/llm-exchanges", _exchange())

    assert resp.json() == {"success": True, "stored": True, "recording": True}
    async with session_factory() as s:
        row = await s.get(LlmExchange, "ex-1")
        blobs = {b.sha256: b.content for b in (await s.scalars(select(LlmBlob))).all()}
    assert (row.task_id, row.model_id, row.provider, row.mode, row.status) == (
        "task-1", "glm-5.3", "openai", "code", "completed",
    )
    assert (row.input_tokens, row.output_tokens, row.issues, row.has_wire) == (10, 2, "", False)
    assert blobs == {_sha("sys"): "sys", _sha("[]"): "[]"}
    payload = json.loads(row.payload)
    # The texts live in llm_blobs; the payload keeps the references.
    assert payload["request"]["system"] == {"sha256": _sha("sys")}
    assert payload["request"]["messages"] == {"keep": 0, "append": [{"role": "user", "content": "hi"}]}


async def test_a_plain_json_body_is_accepted_and_a_duplicate_ignored(authed, db_session, session_factory):
    await _record_on(db_session)

    first = _post(authed, "/api/llm-exchanges", _exchange(), compress=False)
    again = _post(authed, "/api/llm-exchanges", _exchange(response={"text": "changed"}))

    assert first.json()["stored"] is True
    assert again.json() == {"success": True, "stored": False, "recording": True}
    async with session_factory() as s:
        row = await s.get(LlmExchange, "ex-1")
    assert json.loads(row.payload)["response"]["text"] == "hello"


async def test_broken_bodies_are_refused(authed, db_session, monkeypatch):
    from src.routers import llm_exchanges

    await _record_on(db_session)
    headers = {"Content-Type": "application/json", "Content-Encoding": "gzip"}

    assert authed.post("/api/llm-exchanges", content=b"not gzip", headers=headers).status_code == 400
    assert _post(authed, "/api/llm-exchanges", {"id": "x"}).status_code == 422
    wrong = _exchange()
    wrong["request"]["system"] = {"sha256": _sha("other"), "text": "sys"}
    assert _post(authed, "/api/llm-exchanges", wrong).status_code == 422

    monkeypatch.setattr(llm_exchanges, "MAX_INFLATED_BYTES", 1000)
    bomb = gzip.compress(b"{" + b" " * 100_000 + b"}")
    assert authed.post("/api/llm-exchanges", content=bomb, headers=headers).status_code == 413
    monkeypatch.setattr(llm_exchanges, "MAX_BODY_BYTES", 100)
    assert _post(authed, "/api/llm-exchanges", _exchange()).status_code == 413


async def test_the_static_check_runs_at_ingest(authed, db_session, session_factory):
    await _record_on(db_session)
    tools = json.dumps([{"type": "function", "function": {"name": "read_file", "parameters": {
        "type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}}}])
    body = _exchange(response={"toolCalls": [{"id": "c", "name": "read_file", "arguments": '{"mode":"x"}'}]})
    body["request"]["tools"] = {"sha256": _sha(tools), "text": tools}

    _post(authed, "/api/llm-exchanges", body)

    async with session_factory() as s:
        assert (await s.get(LlmExchange, "ex-1")).issues == "missing_parameter"


async def test_an_outcome_refreshes_the_issues_and_the_usage(authed, db_session, session_factory):
    await _record_on(db_session)
    _post(authed, "/api/llm-exchanges", _exchange())

    resp = _post(authed, "/api/llm-exchanges/outcome", {
        "exchangeId": "ex-1",
        "taskId": "task-1",
        "toolResults": [
            {"toolCallId": "c1", "toolName": "read_file", "status": "ok"},
            {"toolCallId": "c2", "toolName": "apply_diff", "status": "diff_error", "note": "No match"},
        ],
        "usage": {"inputTokens": 11, "outputTokens": 7},
    })
    unknown = _post(authed, "/api/llm-exchanges/outcome", {"exchangeId": "nope", "taskId": "t", "toolResults": []})

    assert resp.json() == {"success": True, "stored": True, "recording": True}
    assert unknown.json()["stored"] is False
    async with session_factory() as s:
        row = await s.get(LlmExchange, "ex-1")
    assert row.issues == "tool_failed"
    assert (row.input_tokens, row.output_tokens) == (11, 7)
    assert json.loads(row.outcome)["toolResults"][1] == {
        "toolCallId": "c2", "toolName": "apply_diff", "status": "diff_error", "note": "No match",
    }


async def test_an_outcome_for_someone_elses_exchange_is_not_stored(authed, db_session, session_factory):
    await _record_on(db_session)
    await _record_on(db_session, user_id="user_other")
    _override_current_user(authed.app, user_id="user_other")
    _post(authed, "/api/llm-exchanges", _exchange())
    _override_current_user(authed.app)

    resp = _post(authed, "/api/llm-exchanges/outcome", {"exchangeId": "ex-1", "taskId": "task-1", "toolResults": []})

    assert resp.json()["stored"] is False


# --- the contract with the extension --------------------------------------------------


async def test_the_recorders_uploads_reconstruct_every_request_exactly(authed, db_session, session_factory):
    await _record_on(db_session)
    for item in FIXTURE["exchanges"]:
        if item["accepted"]:
            assert _post(authed, "/api/llm-exchanges", item["body"]).json()["stored"] is True
    for outcome in FIXTURE["outcomes"]:
        _post(authed, "/api/llm-exchanges/outcome", outcome)

    async with session_factory() as s:
        rebuilt = {e.id: e for e in await load_task(s, "user_test", "task-contract", verify_wire=True)}

    accepted = {item["body"]["id"] for item in FIXTURE["exchanges"] if item["accepted"]}
    assert set(rebuilt) == accepted
    for expected in FIXTURE["expected"]:
        if expected["id"] not in accepted:
            continue
        exchange = rebuilt[expected["id"]]
        assert exchange.complete, expected["id"]
        assert exchange.system == expected["system"]
        assert exchange.tools == expected["tools"]
        assert exchange.messages == expected["messages"]
        # The exact HTTP body, byte for byte: same JSON and the recorded hash matches.
        assert exchange.wire_body == json.loads(expected["wireBody"])
        assert exchange.wire_verified is True, expected["id"]
        assert exchange.wire["url"] == "https://llm.example/v1/chat/completions"

    by_sequence = {e.sequence: e for e in rebuilt.values()}
    assert by_sequence[0].issues == []
    assert by_sequence[1].issues == ["api_error"]
    assert by_sequence[2].issues == ["tool_failed"]
    assert by_sequence[4].issues == []
    # The lost fourth upload: the fifth exchange is a full snapshot, not a delta of it.
    assert by_sequence[4].base_id is None


async def test_a_missing_base_makes_the_chain_incomplete(authed, db_session, session_factory):
    await _record_on(db_session)
    first, second, third = (copy.deepcopy(item["body"]) for item in FIXTURE["exchanges"][:3])
    # The first never arrived: the second and third build on it.
    _post(authed, "/api/llm-exchanges", second)
    _post(authed, "/api/llm-exchanges", third)

    async with session_factory() as s:
        rebuilt = await load_task(s, "user_test", "task-contract")

    assert [e.complete for e in rebuilt] == [False, False]
    assert all("incomplete" in e.issues for e in rebuilt)
    assert first["id"] not in {e.id for e in rebuilt}


# --- deletion --------------------------------------------------------------------------


async def test_deleting_a_task_deletes_its_recordings(authed, db_session, session_factory):
    await _record_on(db_session)
    db_session.add(Task(id="task-1", user_id="user_test"))
    await db_session.commit()
    _post(authed, "/api/llm-exchanges", _exchange())
    _post(authed, "/api/llm-exchanges", _exchange(id="ex-other", taskId="task-2"))

    async with session_factory() as s:
        assert await delete_tasks(s, ["task-1"], "user_test") == 1
        await s.commit()

    async with session_factory() as s:
        assert [r.id for r in (await s.scalars(select(LlmExchange))).all()] == ["ex-other"]
        assert {b.task_id for b in (await s.scalars(select(LlmBlob))).all()} == {"task-2"}


async def test_deleting_the_user_deletes_everything(authed, db_session, session_factory):
    await _record_on(db_session)
    _post(authed, "/api/llm-exchanges", _exchange())

    async with session_factory() as s:
        await s.delete(await s.get(User, "user_test"))
        await s.commit()

    assert await _count(session_factory, LlmExchange) == 0
    assert await _count(session_factory, LlmBlob) == 0
    assert await _count(session_factory, DatasetSettings) == 0


async def test_half_an_emoji_does_not_break_the_upload(authed, db_session, session_factory):
    """JavaScript can cut a string between the halves of a surrogate pair; JSON.stringify writes the half escaped."""
    await _record_on(db_session)
    system = "sys \ufffd"  # how Node hashes a lone half: as U+FFFD
    body = json.dumps(_exchange()).replace('"hello"', '"cut \\ud83d"')
    body = body.replace(json.dumps({"sha256": _sha("sys"), "text": "sys"}),
                        json.dumps({"sha256": _sha(system), "text": "sys \\ud83d"}).replace("\\\\", "\\"))

    resp = authed.post("/api/llm-exchanges", content=gzip.compress(body.encode()),
                       headers={"Content-Type": "application/json", "Content-Encoding": "gzip"})

    assert resp.status_code == 200, resp.text
    async with session_factory() as s:
        rebuilt = await load_task(s, "user_test", "task-1")
    assert rebuilt[0].response["text"] == "cut \ufffd"
    assert rebuilt[0].system == system


async def test_a_delta_whose_base_is_gone_asks_for_a_full_snapshot(authed, db_session):
    await _record_on(db_session)
    first, second = (item["body"] for item in FIXTURE["exchanges"][:2])

    assert "resnapshot" not in _post(authed, "/api/llm-exchanges", first).json()
    assert "resnapshot" not in _post(authed, "/api/llm-exchanges", second).json()
    authed.app.dependency_overrides.pop(get_current_user, None)
    _override_current_user(authed.app, user_id="user_other")
    await _record_on(db_session, user_id="user_other")
    third = dict(FIXTURE["exchanges"][2]["body"])

    # The base belongs to another account: not something this user can build on.
    assert _post(authed, "/api/llm-exchanges", third).json()["resnapshot"] is True
